version: "3.7"
services:
  php:
    build: './php/'
    networks:
      - network_labo
    volumes:
      - ./src/:/var/www/html/
      - ./session/:/home/session/
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini

  apache:
    build: './apache/'
    depends_on:
      - php
      - db
    networks:
      - network_labo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/:/var/www/html/

  db:
    image: mysql:5.7.26
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_principale
      MYSQL_USER: utente_principale
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - network_labo
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - network_labo

  phpmyadmin:
    container_name: phpmyadm_labo
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    #restart: always
    volumes:
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 300M
    depends_on:
      - db
    networks:
      - network_labo

  npm:
    container_name: npm_labo
    image: node:16.13
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - network_labo

networks:
  network_labo: